Add the ability to set the user id as one of the usr properties
applicaster/zapp-analytics-plugin-firebase pull request #12
Opened 2020-08-18 08:12 UTC by meravz82

## Description
There is the requisite that analytics are tracked using the identifier from the user. Firebase plugin should specify this parameter when tracking analytics
[IM-502](https://applicaster.atlassian.net/secure/RapidBoard.jspa?rapidView=232&projectKey=IM&modal=detail&selectedIssue=IM-502&quickFilter=552)

## Checklist
* [X] PR is scoped to one task
* [ ] Tests are included
* [ ] Documentation is included

* [X] This PR is not making any UI change
* [ ] This PR is making a UI change
  * [ ] Screenshot(s) included

2020-08-18 10:11 UTC, pablorueda requested changes

2020-08-18 10:11 UTC, PRuedaApplicaster commented on Android/src/main/java/applicaster/analytics/firebase/FirebaseAgent.java
> +                    params.put("user_id", storedUserId);
You should use the method:
setUserId();
https://firebase.google.com/docs/analytics/userid#android

2020-08-18 15:08 UTC, pablorueda approved these changes

2020-08-19 10:32 UTC, lomudi approved these changes
💯

2020-08-19 14:48 UTC, merged